kind: Pod
apiVersion: v1
metadata:
  name: annotations
  annotations:
    buildUrl: "https://jenkins.com/expense"
    imageregistry: "https://hub.docker.com"
spec:
  containers:
    - name: nginx
      image: nginx